version: "1.0"
services:
  activitytracker_api:
    build: . # build the Docker image 
    container_name: activitytrackerapi
    ports:
      - "5000:5000"
    environment:
      - "ASPNETCORE_URLS=http://+:5000"
      - "ASPNETCORE_ENVIRONMENT=Development"